### PR TITLE
Workaround for Integer unification on Ruby 2.4

### PR DESCRIPTION
**Pull request by hsbt**
Ruby 2.4 removed `rb_cFixnum` caused by Integer Unification. Therefore mysql gem is not working with Ruby 2.4.

I added workaround for Integer Unification.

### CODE REVIEW

**Comment by luislavena** [comment]
Hello @hsbt, thank you for the pull request, however cannot merge these changes as I'm not actively maintain this gem any more.

Currently looking for someone to step up and take ownership (well, actually since January 2015).

Hope you understand. Leaving this open in case someone decides to continue this work.

Cheers.

**Comment by hsbt** [comment]
I understood. I'm waiting to come new owner :octocat:

**Comment by luislavena** [comment]
Hello @hsbt, not sure I understood your message. Are you waiting for new owner to step in, or are you offering yourself as new owner?

Please let me know so we can coordinate commit bits and gem push permissions.

Cheers.

**Comment by hsbt** [comment]
Ruby 2.4 is EOL. I have no idea to fix it now.

**Pull request closed without merging**
